title: "[入門]Dockerで構築するnginxハンズオン"
summary: "初心者向けのnginxのハンズオンです。"
topics: ["nginx"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - about
  - setup
  - static-content-delivery
  - alias
  - restrict
  - variable
  - gzip
  - tryfiles
  - php-fpm-tcp
  - php-fpm-unix
